name: Bluesky RSS Bot

on:
  schedule:
        - cron: '0 0,12 * * *'  # Roda à 00:00 e 12:00 UTC
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Limpar cache pip
        run: pip cache purge

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install multiformats==0.1.4.post3  # Versão estável comprovada
          pip install -r requirements.txt --ignore-installed

      - name: Verificar instalação
        run: pip list

      - name: Rodar o script
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: |
          python feeddenoticias.py
