name: Bluesky RSS Bot

on:
  schedule:
    - cron: '0 0,12 * * *'  # Roda à meia-noite e meio-dia UTC
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/MarshalX/atproto.git@main
          pip install feedparser==6.0.10 beautifulsoup4==4.12.0

      - name: Rodar o script
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: |
          python feeddenoticias.py
